config/routes.rb
Rails.application.routes.draw do
  resources :bookmanages
  # get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmanage.rb
class Bookmanage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmanages_controller.rb
class BookmanagesController < ApplicationController
  before_action :set_bookmanage, only: %i[ show edit update destroy ]

  # GET /bookmanages or /bookmanages.json
  def index
    @bookmanages = Bookmanage.all
  end

  # GET /bookmanages/1 or /bookmanages/1.json
  def show
  end

  # GET /bookmanages/new
  def new
    @bookmanage = Bookmanage.new
  end

  # GET /bookmanages/1/edit
  def edit
  end

  # POST /bookmanages or /bookmanages.json
  def create
    @bookmanage = Bookmanage.new(bookmanage_params)

    respond_to do |format|
      if @bookmanage.save
        format.html { redirect_to bookmanage_url(@bookmanage), notice: "Bookmanage was successfully created." }
        format.json { render :show, status: :created, location: @bookmanage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmanages/1 or /bookmanages/1.json
  def update
    respond_to do |format|
      if @bookmanage.update(bookmanage_params)
        format.html { redirect_to bookmanage_url(@bookmanage), notice: "Bookmanage was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmanage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmanage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmanages/1 or /bookmanages/1.json
  def destroy
    @bookmanage.destroy

    respond_to do |format|
      format.html { redirect_to bookmanages_url, notice: "Bookmanage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmanage
      @bookmanage = Bookmanage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmanage_params
      params.require(:bookmanage).permit(:student_id, :fullname, :class_name, :book_id, :book_name, :author_name, :source_name, :bm_number, :first_day, :last_day, :day_number, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmanages_helper.rb
module BookmanagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookmanages/_bookmanage.html.erb
<div id="<%= dom_id bookmanage %>">
  <p>
    <strong>Student:</strong>
    <%= bookmanage.student_id %>
  </p>

  <p>
    <strong>Fullname:</strong>
    <%= bookmanage.fullname %>
  </p>

  <p>
    <strong>Class name:</strong>
    <%= bookmanage.class_name %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= bookmanage.book_id %>
  </p>

  <p>
    <strong>Book name:</strong>
    <%= bookmanage.book_name %>
  </p>

  <p>
    <strong>Author name:</strong>
    <%= bookmanage.author_name %>
  </p>

  <p>
    <strong>Source name:</strong>
    <%= bookmanage.source_name %>
  </p>

  <p>
    <strong>Bm number:</strong>
    <%= bookmanage.bm_number %>
  </p>

  <p>
    <strong>First day:</strong>
    <%= bookmanage.first_day %>
  </p>

  <p>
    <strong>Last day:</strong>
    <%= bookmanage.last_day %>
  </p>

  <p>
    <strong>Day number:</strong>
    <%= bookmanage.day_number %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= bookmanage.note %>
  </p>

</div>

app/views/bookmanages/_form.html.erb
<%= form_with(model: bookmanage) do |form| %>
  <% if bookmanage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bookmanage.errors.count, "error") %> prohibited this bookmanage from being saved:</h2>

      <ul>
        <% bookmanage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :student_id, class: "form-control", placeholder: "Mã HS" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :fullname,class: "form-control", placeholder: "Họ và tên" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :class_name,class: "form-control", placeholder: "Lớp" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :book_id,class: "form-control", placeholder: "Mã sách" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :book_name,class: "form-control", placeholder: "Tên sách" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :author_name,class: "form-control", placeholder: "Tác giả" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :source_name,class: "form-control", placeholder: "Tủ sách" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :bm_number,class: "form-control", placeholder: "Số BM" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :first_day,class: "form-control", placeholder: "Ngày mượn" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :last_day,class: "form-control", placeholder: "Ngày trả" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">
    <%= form.text_field :day_number,class: "form-control", placeholder: "Số ngày" %>
  </div>

  <div class="field form-group" style="margin-bottom: 20px">  
  <%= form.text_field :note,class: "form-control", placeholder: "Ghi chú" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-secondary"%>
  </div>
<% end %>

app/views/bookmanages/edit.html.erb
<h1>Chỉnh sửa</h1>

<%= render "form", bookmanage: @bookmanage %>

<br>

<div>
  <%= link_to "Show", @bookmanage, class:"btn btn-secondary" %> |
  <%= link_to "Quay lại", bookmanages_path, class:"btn btn-dark" %>
</div>

app/views/bookmanages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quản lý sách</h1>

<table class="table table-success table-striped">
<thead class="thead-dark">
      <tr>
        <th>Mã HS</th>
        <th>Họ và tên</th>
        <th>Lớp</th>
        <th>Mã sách</th>
        <th>Tên sách</th>
        <th>Tên tác giả</th>
        <th>Tủ sách</th>
        <th>Số BM</th>
        <th>Ngày mượn</th>
        <th>Ngày trả</th>
        <th>Số ngày</th>
        <th>Ghi chú</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
    <% @bookmanages.each do |bookmanage| %>
    <tr>
      <td><%= bookmanage.student_id %></td>
      <td><%= bookmanage.fullname %></td>
      <td><%= bookmanage.class_name %></td>
      <td><%= bookmanage.book_id %></td>
      <td><%= bookmanage.book_name %></td>
      <td><%= bookmanage.author_name %></td>
      <td><%= bookmanage.source_name %></td>
      <td><%= bookmanage.bm_number %></td>
      <td><%= bookmanage.first_day %></td>
      <td><%= bookmanage.last_day %></td>
      <td><%= bookmanage.day_number %></td>
      <td><%= bookmanage.note %></td>
      <td><%= link_to "Show", bookmanage, class: "btn btn-info" %></td>
    </tr>
<% end %>
    </tbody>
</table>

<%= link_to "Thêm mới", new_bookmanage_path, class: "btn btn-primary" %>

app/views/bookmanages/new.html.erb
<h1>Thêm mới</h1>

<%= render "form", bookmanage: @bookmanage %>

<br>

<div>
  <%= link_to "Quay lại", bookmanages_path, class: "btn btn-dark" %>
</div>

app/views/bookmanages/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4">
    
        <%= @bookmanage.fullname %>
  </h1>
  <p class="lead">
    <%= @bookmanage.student_id %> |
    <%= @bookmanage.class_name %>  | 
    <%= @bookmanage.book_id %>  |  
    <%= @bookmanage.book_name %>  |
    <%= @bookmanage.author_name %>  |
    <%= @bookmanage.source_name %>  |
    <%= @bookmanage.bm_number %>  |
    <%= @bookmanage.first_day %>  |
    <%= @bookmanage.last_day %>  |
    <%= @bookmanage.day_number %>  |
    <%= @bookmanage.note %>  |

  </p>
  <%= link_to "Chỉnh sửa", edit_bookmanage_path(@bookmanage), class:"btn btn-warning" %> 
  <%= link_to "Quay lại", bookmanages_path, class:"btn btn-dark" %>

  <%= button_to "Xóa", @bookmanage, method: :delete , class:"btn btn-danger", style:"margin-top: 20px"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
  <%= link_to 'Book', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Manager", bookmanages_path, class:"nav-link active"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>BookManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
  <%= render 'home/header'%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>